### ISSUE TITLE
Bug: Does not work for some item types in Papers with Zotero

### ISSUE THREAD

**Issue by SeptemberHX** [SeptemberHX/joplin-plugin-bundle#11]
Bug: Does not work for some item types in Papers with Zotero

**Comment by cherryfrog856** [comment]
Book chapter shows the following metadata in zotero: Title, Item Type, Editor, Author, Book title, year, publisher, ISBN. 
In Joplin, only the Title and the editors and authors are shown.

**Comment by cherryfrog856** [comment]
For a conference paper with a lot of metadata (Conference, Date, Doi...) only the Title, Authors and abstract are shown.

**Comment by SeptemberHX** [comment]
> For a conference paper with a lot of metadata (Conference, Date, Doi...) only the Title, Authors and abstract are shown.

Yes, it is designed to only show: Title, Journal/Conference Name, Year, Authors, Tags, and Abstract

**Comment by cherryfrog856** [comment]
I agree, however for the conference papers, the conference name is not displayed.

**Comment by SeptemberHX** [comment]
> I agree, however for the conference papers, the conference name is not displayed.

It should be fixed in the new attached plugin file.

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9666521/com.septemberhx.pluginBundle.jpl.zip)

**Comment by SeptemberHX** [comment]
Can you share the doi? I have no book chapter item to test

**Comment by cherryfrog856** [comment]
[https://link.springer.com/chapter/10.1007/978-3-662-46018-4_2](Book chapter)
The link to download only the chapter is a bit further down that page

**Comment by SeptemberHX** [comment]
It should show book title for book sections now.

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9666757/com.septemberhx.pluginBundle.jpl.zip)

**Comment by cherryfrog856** [comment]
Yes it does! Thanks a lot!

**Comment by Shamp0o** [comment]
For some reason, installation via the file doesn't work for me (on MacOS). One item that was causing problems for me was the following: https://arxiv.org/abs/1802.03426
When saving this to Zotero via the browser plugin, it creates a Preprint Item type that doesn't work with the plugin. Again, I wasn't able to run the new version linked in this issue, so I cannot say whether or not the fix works for me.

**Comment by cherryfrog856** [comment]
re install on macos: I had the problem that the MacOs archive app would extract it to some folders. It helped doing the unzip via the terminal.

**Comment by Shamp0o** [comment]
I managed to install the zip posted here but the problem still exists. The above linked paper still cannot be inserted.

**Comment by SeptemberHX** [comment]
> I managed to install the zip posted here but the problem still exists. The above linked paper still cannot be inserted.

It should work now

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9691768/com.septemberhx.pluginBundle.jpl.zip)

**Comment by bepolymathe** [comment]
Is this the desired behavior? With the "book" entries the date does not appear in Joplin 

![image](https://user-images.githubusercontent.com/29939805/193836633-42e2250a-a117-41b1-89b8-51e0f8891eb6.png)


![image](https://user-images.githubusercontent.com/29939805/193836538-683dbd0b-b329-4a07-902f-724e42435cdf.png)

**Comment by SeptemberHX** [comment]
No, the date should also show for `book` items.

**Comment by Shamp0o** [comment]
> It should work now

Sorry for the late reply. Unfortunately the link I posted above still doesn't work for me.

**Comment by SeptemberHX** [comment]
Does the plugin work for other items? If so, you can try to sync all your items by 'Tools -> Papers -> Sync'.

If not, does there exist error message in the dev tools? You can check it by 'Help -> Toggle Dev Tools' and try to find message in red color.

**Comment by BioFacLay** [comment]
Other items work. When trying to import the item from the link above I get the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at /home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315
    at Generator.next (<anonymous>)
    at /home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315
    at new Promise (<anonymous>)
    at n (/home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315)
    at /home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315
    at Object.<anonymous> (/home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315)
    at Generator.next (<anonymous>)
    at /home/myuser/.config/joplin-desktop/tmp/plugin_com.septemberhx.pluginBundle.js:315
    at new Promise (<anonymous>)
```

**Comment by SeptemberHX** [comment]
How you import it ? By add the doi `10.48550/arXiv.1802.03426` directly, or download the pdf file and drag it into zotero?

**Comment by Shamp0o** [comment]
Just realized I was logged in with the wrong account. 

I imported the item with the Zotero connector (Firefox) with the above linked site, not the pdf, open (the recommended Zotero way).

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9839933/com.septemberhx.pluginBundle.jpl.zip)

Please test again with the new attached file. This problem is caused by some missing information (volume) if you import it with Zotero connector. It should be fixed now.

**Comment by Shamp0o** [comment]
Now it's working. Thanks for the fix.
